=== UDA-Corporation/UDA_app/Diseño/XML/BDD(Clasificacion).xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="liga" type="tipo_liga"/>
    <xs:complexType name="tipo_liga">
        <xs:sequence>
            <xs:element type="tipo_clasificacion" name="clasificacion"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipo_clasificacion">
        <xs:sequence>
            <xs:element type="tipo_equipo" name="equipo" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipo_equipo">
        <xs:sequence>
            <xs:element type="xs:string" name="nombre"/>
            <xs:element type="xs:string" name="puntos"/>
            <xs:element type="xs:string" name="puesto"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="codEquipo" use="optional"/>
    </xs:complexType>
</xs:schema>

=== UDA-Corporation/UDA_app/Diseño/XML/BDD(Clasificacion).xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<liga xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BDD(Clasificacion).xsd">
    <clasificacion>
        <equipo codEquipo="_44">
            <nombre></nombre>
            <puntos></puntos>
            <puesto></puesto>
        </equipo>
        <equipo codEquipo="_43">
            <nombre></nombre>
            <puntos></puntos>
            <puesto></puesto>
        </equipo>
    </clasificacion>
</liga>

=== UDA-Corporation/UDA_app/Java/UDA_app/BDD(Clasificacion).xml
<?xml version="1.0" encoding="UTF-8"?>
<liga xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BDD(Clasificacion).xsd">
    <clasificacion>
        <equipo codEquipo="12" puesto="2" puntos="30">Destroy3r</equipo>
        <equipo codEquipo="12" puesto="2" puntos="30">Test2</equipo>
        <equipo codEquipo="12" puesto="2" puntos="30">Test3</equipo>
        <equipo codEquipo="12" puesto="2" puntos="30">Test4</equipo>
        <equipo codEquipo="12" puesto="2" puntos="30">Test5</equipo>
        <equipo codEquipo="12" puesto="2" puntos="30">Test6</equipo>
    </clasificacion>
    <clasificacion>
        <equipo codEquipo="1" puesto="3" puntos="0">D3STROY</equipo>
        <equipo codEquipo="2" puesto="2" puntos="0">FNATICX</equipo>
        <equipo codEquipo="3" puesto="1" puntos="0">BIMBA</equipo>
        <equipo codEquipo="4" puesto="3" puntos="0">UOL</equipo>
        <equipo codEquipo="5" puesto="2" puntos="0">Team Liquid</equipo>
        <equipo codEquipo="6" puesto="1" puntos="0">Renegades</equipo>
        <equipo codEquipo="7" puesto="3" puntos="0">Cloud9</equipo>
        <equipo codEquipo="8" puesto="2" puntos="0">Origen</equipo>
    </clasificacion>
</liga>
