=== UDA-Corporation/UDA_app/Diseño/XML/BDD(Jornadas).xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="liga" type="tipo_liga"/>
    <xs:complexType name="tipo_liga">
        <xs:sequence>
            <xs:element type="tipo_jornada" name="jornada"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipo_jornada">
        <xs:sequence>
            <xs:element type="tipo_partido" name="partido"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="codigoJornada"/>
        <xs:attribute type="xs:string" name="fechaI"/>
        <xs:attribute type="xs:string" name="fechaF"/>
    </xs:complexType>
    <xs:complexType name="tipo_partido">
        <xs:sequence>
            <xs:element type="xs:string" name="resultado"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="equipo_local"/>
        <xs:attribute type="xs:string" name="equipo_visitante"/>
      </xs:complexType>
</xs:schema>

=== UDA-Corporation/UDA_app/App/UDA_app/BDD(Jornadas).xml
<?xml version="1.0" encoding="UTF-8"?>
<liga xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BDD(Jornadas).xsd">
    <jornada codigoJornada="1" fechaFinal="20-11-2018" fechaInicio="10-10-2018">
        <partido equipo1="1" equipo2="2">
            <resultado>10-20</resultado>
        </partido>
        <partido equipo1="3" equipo2="4">
            <resultado>30-20</resultado>
        </partido>
        <partido equipo1="3" equipo2="4">
            <resultado>30-20</resultado>
        </partido>
        <partido equipo1="3" equipo2="4">
            <resultado>30-20</resultado>
        </partido>
    </jornada>
    <jornada codigoJornada="2" fechaFinal="20-11-2018" fechaInicio="10-10-2018">
        <partido equipo1="3" equipo2="4">
            <resultado>30-20</resultado>
        </partido>
        <partido equipo1="3" equipo2="4">
            <resultado>30-20</resultado>
        </partido>
        <partido equipo1="3" equipo2="4">
            <resultado>30-20</resultado>
        </partido>
        <partido equipo1="3" equipo2="4">
            <resultado>30-20</resultado>
        </partido>
    </jornada>
</liga>
